import food_1 from './food_1.png';
import food_2 from './food_2.png';
import food_3 from './food_3.png';
import food_4 from './food_4.png';
import food_5 from './food_5.png';
import food_6 from './food_6.png';
import food_7 from './food_7.png';
import food_8 from './food_8.png';
import food_9 from './food_9.png';
import food_10 from './food_10.png';
import food_11 from './food_11.png';
import food_12 from './food_12.png';
import food_13 from './food_13.png';
import food_14 from './food_14.png';
import food_15 from './food_15.png';
import food_16 from './food_16.png';
import food_17 from './food_17.png';
import food_18 from './food_18.png';
import food_19 from './food_19.png';
import food_20 from './food_20.png';
import food_21 from './food_21.png';
import food_22 from './food_22.png';
import food_23 from './food_23.png';
import food_24 from './food_24.png';
import food_25 from './food_25.png';
import food_26 from './food_26.png';
import food_27 from './food_27.png';
import food_28 from './food_28.png';
import food_29 from './food_29.png';
import food_30 from './food_30.png';
import food_31 from './food_31.png';
import food_32 from './food_32.png';


type FoodItem = {
    _id: string;
    name: string;
    image: string;
    price: number;
    description: string;
    category: string;
    longDescription: string;
    ingredients: string;
    storageInstructions : string;
    nutrition : string;
    size : string;
    
}

export const food_list: FoodItem[] = [
    {
        _id: "1",
        name: "Greek salad",
        image: food_1,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Salad",
        ingredients : "lorem 1",
        storageInstructions : "เดี๋ยวค่อยใส่ 1" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "2",
        name: "Veg salad",
        image: food_2,
        price: 18,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Salad",
        ingredients : "lorem 2",
        storageInstructions : "เดี๋ยวค่อยใส่ 2" ,
        nutrition : "008" ,
        size : "57" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "3",
        name: "Clover Salad",
        image: food_3,
        price: 16,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Salad",
        ingredients : "lorem 3",
        storageInstructions : "เดี๋ยวค่อยใส่ 3" ,
        nutrition : "009" ,
        size : "58" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "4",
        name: "Chicken Salad",
        image: food_4,
        price: 24,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Salad",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "5",
        name: "Lasagna Rolls",
        image: food_5,
        price: 14,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Rolls",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "6",
        name: "Peri Peri Rolls",
        image: food_6,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Rolls",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "7",
        name: "Chicken Rolls",
        image: food_7,
        price: 20,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Rolls",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "8",
        name: "Veg Rolls",
        image: food_8,
        price: 15,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Rolls",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "9",
        name: "Ripple Ice Cream",
        image: food_9,
        price: 14,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Deserts",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "10",
        name: "Fruit Ice Cream",
        image: food_10,
        price: 22,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Deserts",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "11",
        name: "Jar Ice Cream",
        image: food_11,
        price: 10,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Deserts",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "12",
        name: "Vanilla Ice Cream",
        image: food_12,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Deserts",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "13",
        name: "Chicken Sandwich",
        image: food_13,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Sandwich",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "14",
        name: "Vegan Sandwich",
        image: food_14,
        price: 18,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Sandwich",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "15",
        name: "Grilled Sandwich",
        image: food_15,
        price: 16,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Sandwich",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "16",
        name: "Bread Sandwich",
        image: food_16,
        price: 24,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Sandwich",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "17",
        name: "Cup Cake",
        image: food_17,
        price: 14,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Cake",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "18",
        name: "Vegan Cake",
        image: food_18,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Cake",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "19",
        name: "Butterscotch Cake",
        image: food_19,
        price: 20,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Cake",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "20",
        name: "Sliced Cake",
        image: food_20,
        price: 15,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Cake",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "21",
        name: "Garlic Mushroom",
        image: food_21,
        price: 14,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pure Veg",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "22",
        name: "Fried Cauliflower",
        image: food_22,
        price: 22,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pure Veg",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "23",
        name: "Mix Veg Pulao",
        image: food_23,
        price: 10,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pure Veg",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "24",
        name: "Rice Zucchini",
        image: food_24,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pure Veg",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "25",
        name: "Cheese Pasta",
        image: food_25,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pasta",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "26",
        name: "Tomato Pasta",
        image: food_26,
        price: 18,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pasta",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "27",
        name: "Indian Pasta",
        image: food_27,
        price: 16,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pasta",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "28",
        name: "Corn Pasta",
        image: food_28,
        price: 24,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Pasta",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "29",
        name: "Chicken Soup",
        image: food_29,
        price: 14,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Soup",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "30",
        name: "Mix Veg Soup",
        image: food_30,
        price: 12,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Soup",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "31",
        name: "Sweet Corn Soup",
        image: food_31,
        price: 20,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Soup",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    },
    {
        _id: "32",
        name: "Pumpkin Soup",
        image: food_32,
        price: 15,
        description: "Food provides essential nutrients for overall health and well-being",
        category: "Soup",
        ingredients : "lorem",
        storageInstructions : "เดี๋ยวค่อยใส่" ,
        nutrition : "007" ,
        size : "56" ,
        longDescription: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Odio cum perferendis iste quo libero sint tenetur repudiandae! Vitae dignissimos reprehenderit excepturi quidem eligendi eius, corporis, expedita dicta facilis adipisci exercitationem!",
    }
];
